name: Local CI-CD Pipeline
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
     # - name: Docker Login
      #  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      - name: Build Docker Image
        run: |
          docker build -t omprakash13890/devops:${{ github.run_number }} .
          docker push omprakash13890/devops:${{ github.run_number }}
 
      - name: Terraform Init
        working-directory: infra
        run: terraform init
 
      - name: Terraform Validate
        working-directory: infra
        run: terraform validate
 
      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -var="image_tag=${{ github.run_number }}"
 
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -var="image_tag=${{ github.run_number }}"
 
      - name: Wait for Deployment
        run: kubectl rollout status deployment/devops-app
 
      - name: Verify Pods
        run: kubectl get pods -o wide
